CREATE TABLE CE_CUSTOMERS (
    CUSTOMER_ID NUMBER,
    CUSTOMER_SRCID VARCHAR2(250) NOT NULL,
    SOURCE_SYSTEM VARCHAR2(50) NOT NULL,
    SOURCE_TABLE VARCHAR2(50) NOT NULL,
    CUSTOMER_FIRST_NAME VARCHAR2(100) NOT NULL,
    CUSTOMER_LAST_NAME VARCHAR2(100) NOT NULL,
    CUSTOMER_COMPANY_NAME VARCHAR2(100) NOT NULL,
    CUSTOMER_CITY_ID NUMBER NOT NULL,
    IS_COMPANY VARCHAR2(4) NOT NULL,
    INSERT_DT DATE NOT NULL,
    UPDATE_DT DATE NOT NULL,
    CONSTRAINT PK_CUSTOMERS PRIMARY KEY(CUSTOMER_ID),
    CONSTRAINT FK_CUSTOMERS FOREIGN KEY (CUSTOMER_CITY_ID)
    REFERENCES CE_CITIES(CITY_ID)
);

CREATE OR REPLACE PUBLIC SYNONYM CE_CUSTOMERS FOR BL_3NF.CE_CUSTOMERS;
GRANT SELECT, INSERT, UPDATE, DELETE ON BL_3NF.CE_CUSTOMERS TO BL_CL;