CREATE SEQUENCE SEQ_DIM_PRODUCTS_SCD_SURR
    START WITH 1;
    
GRANT SELECT ON SEQ_DIM_PRODUCTS_SCD_SURR TO BL_CL;
CREATE PUBLIC SYNONYM SEQ_DIM_PRODUCTS_SCD_SURR FOR BL_DM.SEQ_DIM_PRODUCTS_SCD_SURR;