INSERT INTO BL_3NF.CE_PRODUCTS_SCD 
( 
	PRODUCT_SRCID, 
	SOURCE_SYSTEM, 
	SOURCE_TABLE, 
	PRODUCT_NAME, 
	PRODUCT_CATEGORY_ID, 
	PRODUCT_WEIGHT_G, 
	PRODUCT_LENGTH_CM, 
	PRODUCT_HEIGHT_CM, 
	PRODUCT_WIDTH_CM
)
WITH TEMP_Q AS 
(
    SELECT 
        MAX(INSERT_DT) AS MAX_DATE
    FROM BL_3NF.CE_PRODUCTS_SCD
)
SELECT 
    PRODUCT_ID,
    'SA_SOURCE_SYSTEM_RETAIL' AS SOURCE_SYSTEM,
    'SA_PRODUCTS' AS SOURCE_TABLE,
    PRODUCT_NAME,
    PRODUCT_CATEGORY_ID,
    PRODUCT_WEIGHT_G, 
	PRODUCT_LENGTH_CM, 
	PRODUCT_HEIGHT_CM, 
	PRODUCT_WIDTH_CM
FROM SA_SOURCE_SYSTEM_RETAIL.SA_PRODUCTS
WHERE INSERT_DATE > (SELECT MAX_DATE FROM TEMP_Q) AND 
      PRODUCT_ID NOT IN (
                            SELECT 
                                PRODUCT_SRCID
                            FROM BL_3NF.CE_PRODUCTS_SCD 
                        );
                        
COMMIT;