INSERT INTO BL_3NF.CE_PRODUCTS_SCD 
(
    PRODUCT_ID, 
	PRODUCT_SRCID, 
	SOURCE_SYSTEM, 
	SOURCE_TABLE, 
	PRODUCT_NAME, 
	PRODUCT_CATEGORY_ID, 
	PRODUCT_WEIGHT_G, 
	PRODUCT_LENGTH_CM, 
	PRODUCT_HEIGHT_CM, 
	PRODUCT_WIDTH_CM, 
	START_DT, 
	END_DT, 
	IS_ACTIVE, 
	INSERT_DT
)
VALUES (-1, '-99', 'N/A', 'N/A', 'N/A', -1, -99, -99, -99, -99, 
TO_DATE('1990-01-01', 'YYYY-MM-DD'), TO_DATE('9999-12-31', 'YYYY-MM-DD'),
'N/A', TO_DATE('1990-01-01', 'YYYY-MM-DD'));

COMMIT;