CREATE TABLE CE_STATES (
    STATE_ID NUMBER,
    STATE_SRCID NUMBER,
    SOURCE_SYSTEM VARCHAR2(50) NOT NULL,
    SOURCE_TABLE VARCHAR2(50) NOT NULL,
    STATE_NAME VARCHAR2(50) NOT NULL,
    STATE_COUNTRY_ID NUMBER,
    INSERT_DT DATE,
    UPDATE_DT DATE,
    CONSTRAINT PK_STATES PRIMARY KEY(STATE_ID),
    CONSTRAINT FK_STATES FOREIGN KEY (STATE_COUNTRY_ID)
    REFERENCES CE_COUNTRIES(COUNTRY_ID)
);

CREATE OR REPLACE PUBLIC SYNONYM CE_STATES FOR BL_3NF.CE_STATES;
GRANT SELECT, INSERT, UPDATE, DELETE ON BL_3NF.CE_STATES TO BL_CL;