CREATE TABLE CE_PRODUCTS_CATEGORIES_SCD (
    PRODUCT_CATEGORY_ID NUMBER,
    PRODUCT_CATEGORY_SRCID NUMBER,
    SOURCE_SYSTEM VARCHAR2(50) NOT NULL,
    SOURCE_TABLE VARCHAR2(50) NOT NULL,
    PRODUCT_CATEGORY_NAME VARCHAR2(100) NOT NULL,
    PRODUCT_CATEGORY_MARGIN_RATE NUMBER NOT NULL,
    START_DT DATE NOT NULL,
    END_DT  DATE NOT NULL,
    IS_ACTIVE VARCHAR2(4) NOT NULL,
    INSERT_DT DATE NOT NULL,
    CONSTRAINT PK_PRODUCTS_CATEGORIES PRIMARY KEY(PRODUCT_CATEGORY_ID, START_DT)
);

CREATE OR REPLACE PUBLIC SYNONYM CE_PRODUCTS_CATEGORIES_SCD FOR BL_3NF.CE_PRODUCTS_CATEGORIES_SCD;
GRANT SELECT, INSERT, UPDATE, DELETE ON BL_3NF.CE_PRODUCTS_CATEGORIES_SCD TO BL_CL;