CREATE TABLE EXT_CUSTOMERS_BUSINESS (
  CUSTOMER_ID	          VARCHAR2(250),
  COMPANY_NAME            VARCHAR2(250),
  COMPANY_CITY	          VARCHAR2(250),
  COMPANY_STATE          VARCHAR2(250)
)
ORGANIZATION EXTERNAL (
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY EXT_DIR_BUSINESS_DATA
  ACCESS PARAMETERS (
    RECORDS DELIMITED BY NEWLINE 
    SKIP 1
    FIELDS TERMINATED BY ','
    OPTIONALLY ENCLOSED BY '"'
    MISSING FIELD VALUES ARE NULL
  )
  LOCATION ('customers_business.csv')
)
REJECT LIMIT UNLIMITED;

CREATE OR REPLACE PUBLIC SYNONYM EXT_CUSTOMERS_BUSINESS FOR SA_SOURCE_SYSTEM_BUSINESS.EXT_CUSTOMERS_BUSINESS;
GRANT SELECT ON EXT_CUSTOMERS_BUSINESS TO BL_CL;