CREATE SEQUENCE BL_3NF.SEQ_LOGISTIC_PARTNERS_SURR
    START WITH 1;
    
GRANT SELECT ON BL_3NF.SEQ_LOGISTIC_PARTNERS_SURR TO BL_CL;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_LOGISTIC_PARTNERS_SURR FOR BL_3NF.SEQ_LOGISTIC_PARTNERS_SURR;