CREATE TABLE CE_SALES (
    SALE_ID NUMBER,
    SALE_SRCID VARCHAR2(250) NOT NULL,
    SOURCE_SYSTEM VARCHAR2(50) NOT NULL,
    SOURCE_TABLE VARCHAR2(50) NOT NULL,
    PRODUCT_ID NUMBER NOT NULL,
    CUSTOMER_ID NUMBER NOT NULL,
    SUPPLIER_ID NUMBER NOT NULL,
    LOGISTIC_PARTNER_ID NUMBER NOT NULL,
    PAYMENT_TYPE_ID NUMBER NOT NULL,
    AMOUNT_VALUE NUMBER NOT NULL,
    COST_VALUE NUMBER NOT NULL,
    PURCHASE_DATE DATE NOT NULL,
    INSERT_DT DATE NOT NULL,
    UPDATE_DT DATE NOT NULL,
    CONSTRAINT PK_SALES PRIMARY KEY(SALE_ID),
    CONSTRAINT FK_SALES_CUSTOMER FOREIGN KEY (CUSTOMER_ID)
    REFERENCES CE_CUSTOMERS(CUSTOMER_ID),
    CONSTRAINT FK_SALES_SUPPLIER FOREIGN KEY (SUPPLIER_ID)
    REFERENCES CE_SUPPLIERS(SUPPLIER_ID),
    CONSTRAINT FK_SALES_LOGISTIC_PARTNER FOREIGN KEY (LOGISTIC_PARTNER_ID)
    REFERENCES CE_LOGISTIC_PARTNERS(LOGISTIC_PARTNER_ID),
    CONSTRAINT FK_SALES_PAYMENT_TYPE FOREIGN KEY (PAYMENT_TYPE_ID)
    REFERENCES CE_PAYMENT_TYPES(PAYMENT_TYPE_ID)
)
PARTITION BY RANGE(PURCHASE_DATE)
(
  PARTITION SALES_07_19 VALUES LESS THAN (TO_DATE('2019-08-01', 'YYYY-MM-DD')),
  PARTITION SALES_08_19 VALUES LESS THAN (TO_DATE('2019-09-01', 'YYYY-MM-DD')),
  PARTITION SALES_09_19 VALUES LESS THAN (TO_DATE('2019-10-01', 'YYYY-MM-DD')),
  PARTITION SALES_10_19 VALUES LESS THAN (TO_DATE('2019-11-01', 'YYYY-MM-DD')),
  PARTITION SALES_11_19 VALUES LESS THAN (TO_DATE('2019-12-01', 'YYYY-MM-DD')),
  PARTITION SALES_12_19 VALUES LESS THAN (TO_DATE('2020-01-01', 'YYYY-MM-DD')),
  PARTITION SALES_01_20 VALUES LESS THAN (TO_DATE('2020-02-01', 'YYYY-MM-DD')),
  PARTITION SALES_02_20 VALUES LESS THAN (TO_DATE('2020-03-01', 'YYYY-MM-DD')),
  PARTITION SALES_03_20 VALUES LESS THAN (TO_DATE('2020-04-01', 'YYYY-MM-DD')),
  PARTITION SALES_04_20 VALUES LESS THAN (TO_DATE('2020-05-01', 'YYYY-MM-DD')),
  PARTITION SALES_05_20 VALUES LESS THAN (TO_DATE('2020-06-01', 'YYYY-MM-DD')),
  PARTITION SALES_06_20 VALUES LESS THAN (TO_DATE('2020-07-01', 'YYYY-MM-DD')),
  PARTITION SALES_07_20 VALUES LESS THAN (TO_DATE('2020-08-01', 'YYYY-MM-DD')),
  PARTITION SALES_08_20 VALUES LESS THAN (TO_DATE('2020-09-01', 'YYYY-MM-DD')),
  PARTITION SALES_09_20 VALUES LESS THAN (TO_DATE('2020-10-01', 'YYYY-MM-DD')),
  PARTITION SALES_10_20 VALUES LESS THAN (TO_DATE('2020-11-01', 'YYYY-MM-DD')),
  PARTITION SALES_11_20 VALUES LESS THAN (TO_DATE('2020-12-01', 'YYYY-MM-DD')),
  PARTITION SALES_12_20 VALUES LESS THAN (TO_DATE('2021-01-01', 'YYYY-MM-DD')),
  PARTITION SALES_01_21 VALUES LESS THAN (TO_DATE('2021-02-01', 'YYYY-MM-DD')),
  PARTITION SALES_MAX_DATE VALUES LESS THAN (maxvalue)
);

CREATE OR REPLACE PUBLIC SYNONYM CE_SALES FOR BL_3NF.CE_SALES;
GRANT SELECT, INSERT, UPDATE, DELETE ON BL_3NF.CE_SALES TO BL_CL;