INSERT INTO BL_3NF.CE_COUNTRIES 
(
    COUNTRY_SRCID,
    SOURCE_SYSTEM,
    SOURCE_TABLE,
    COUNTRY_NAME
)

WITH TEMP_Q AS 
(
    SELECT 
        MAX(insert_dt) AS MAX_DATE
    FROM BL_3NF.CE_COUNTRIES
)
SELECT DISTINCT
    COUNTRY_ID,
    'SA_SOURCE_SYSTEM_RETAIL',
    'SA_OLIST_GEO',
    COUNTRY_NAME
FROM SA_SOURCE_SYSTEM_RETAIL.SA_OLIST_GEO
WHERE INSERT_DATE > (SELECT MAX_DATE FROM TEMP_Q)
AND COUNTRY_ID NOT IN (
                        SELECT
                            COUNTRY_SRCID
                        FROM BL_3NF.CE_COUNTRIES  
                       )
;

COMMIT;