INSERT INTO BL_3NF.CE_PRODUCTS_CATEGORIES_SCD
( 
	PRODUCT_CATEGORY_SRCID, 
	SOURCE_SYSTEM, 
	SOURCE_TABLE, 
	PRODUCT_CATEGORY_NAME, 
	PRODUCT_CATEGORY_MARGIN_RATE
)
WITH TEMP_Q AS 
(
    SELECT 
        MAX(INSERT_DT) AS MAX_DATE
    FROM BL_3NF.CE_PRODUCTS_CATEGORIES_SCD
)
SELECT DISTINCT
    PRODUCT_CATEGORY_ID,
    'SA_SOURCE_SYSTEM_RETAIL' AS SOURCE_SYSTEM,
    'SA_PRODUCTS' AS SOURCE_TABLE,
    PRODUCT_CATEGORY_NAME_ENGLISH,
    PRODUCT_CATEGORY_MARGIN_RATE
FROM SA_SOURCE_SYSTEM_RETAIL.SA_PRODUCTS
WHERE INSERT_DATE > (SELECT MAX_DATE FROM TEMP_Q)
AND PRODUCT_CATEGORY_ID NOT IN (
                                    SELECT 
                                        PRODUCT_CATEGORY_SRCID
                                    FROM BL_3NF.CE_PRODUCTS_CATEGORIES_SCD
                                );
                                
COMMIT;