CREATE TABLE CE_PRODUCTS_SCD (
    PRODUCT_ID NUMBER,
    PRODUCT_SRCID VARCHAR2(100) NOT NULL,
    SOURCE_SYSTEM VARCHAR2(50) NOT NULL,
    SOURCE_TABLE VARCHAR2(50) NOT NULL,
    PRODUCT_NAME VARCHAR2(100) NOT NULL,
    PRODUCT_CATEGORY_ID NUMBER NOT NULL,
    PRODUCT_WEIGHT_G  NUMBER NOT NULL,
    PRODUCT_LENGTH_CM NUMBER NOT NULL,
    PRODUCT_HEIGHT_CM NUMBER NOT NULL,
    PRODUCT_WIDTH_CM  NUMBER NOT NULL,
    START_DT DATE NOT NULL,
    END_DT  DATE NOT NULL,
    IS_ACTIVE VARCHAR2(4) NOT NULL,
    INSERT_DT DATE NOT NULL,
    CONSTRAINT PK_PRODUCTS PRIMARY KEY(PRODUCT_ID, START_DT)

);

CREATE OR REPLACE PUBLIC SYNONYM CE_PRODUCTS_SCD FOR BL_3NF.CE_PRODUCTS_SCD;
GRANT SELECT, INSERT, UPDATE, DELETE ON BL_3NF.CE_PRODUCTS_SCD TO BL_CL;