CREATE TABLE SA_OLIST_GEO (
  CITY_ID       NUMBER,
  CITY_NAME     VARCHAR2(250),
  STATE_ID      NUMBER,
  STATE_NAME    VARCHAR2(250),
  COUNTRY_ID    NUMBER,
  COUNTRY_NAME  VARCHAR2(250),
  INSERT_DATE   DATE DEFAULT CURRENT_DATE
);

GRANT SELECT, INSERT, UPDATE, DELETE ON SA_OLIST_GEO TO BL_CL;
CREATE OR REPLACE PUBLIC SYNONYM SA_OLIST_GEO FOR SA_SOURCE_SYSTEM_RETAIL.SA_OLIST_GEO;