CREATE TABLE DIM_SUPPLIERS (
    SUPPLIER_SURR_ID     NUMBER,
    SUPPLIER_ID          NUMBER NOT NULL,
    SOURCE_SYSTEM        VARCHAR2(100) NOT NULL,
    SOURCE_TABLE         VARCHAR2(100) NOT NULL,
    SUPPLIER_NAME        VARCHAR2(100) NOT NULL,
    SUPPLIER_CITY_ID     NUMBER NOT NULL,
    SUPPLIER_CITY_NAME   VARCHAR2(50) NOT NULL,
    SUPPLIER_STATE_ID    NUMBER NOT NULL,
    SUPPLIER_STATE_NAME  VARCHAR2(50) NOT NULL,
    INSERT_DT            DATE NOT NULL,
    UPDATE_DT            DATE NOT NULL,
    CONSTRAINT PK_DIM_SUPPLIERS PRIMARY KEY (SUPPLIER_SURR_ID)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON DIM_SUPPLIERS TO BL_CL;
CREATE PUBLIC SYNONYM DIM_SUPPLIERS FOR BL_DM.DIM_SUPPLIERS;