CREATE TABLE CE_PAYMENT_TYPES (
    PAYMENT_TYPE_ID NUMBER,
    PAYMENT_TYPE_SRCID NUMBER,
    SOURCE_SYSTEM VARCHAR2(50) NOT NULL,
    SOURCE_TABLE VARCHAR2(50) NOT NULL,
    PAYMENT_TYPE_NAME VARCHAR2(50) NOT NULL,
    INSERT_DT DATE NOT NULL,
    UPDATE_DT DATE NOT NULL,
    CONSTRAINT PK_PAYMENT_TYPES PRIMARY KEY(PAYMENT_TYPE_ID)
);

CREATE OR REPLACE PUBLIC SYNONYM CE_PAYMENT_TYPES FOR BL_3NF.CE_PAYMENT_TYPES;
GRANT SELECT, INSERT, UPDATE, DELETE ON BL_3NF.CE_PAYMENT_TYPES TO BL_CL;