CREATE TABLE EXT_OLIST_GEO (
  CITY_ID       VARCHAR2(250),
  CITY_NAME     VARCHAR2(250),
  STATE_ID      VARCHAR2(250),
  STATE_NAME    VARCHAR2(250),
  COUNTRY_ID    VARCHAR2(250),
  COUNTRY_NAME  VARCHAR2(250)     
)
ORGANIZATION EXTERNAL (
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY EXT_DIR_RETAIL_DATA
  ACCESS PARAMETERS (
    RECORDS DELIMITED BY NEWLINE 
    SKIP 1
    FIELDS TERMINATED BY ','
    OPTIONALLY ENCLOSED BY '"'
    MISSING FIELD VALUES ARE NULL
  )
  LOCATION ('olist_geo.csv')
)
REJECT LIMIT UNLIMITED;

GRANT SELECT ON EXT_OLIST_GEO TO BL_CL;
CREATE OR REPLACE PUBLIC SYNONYM EXT_OLIST_GEO FOR SA_SOURCE_SYSTEM_RETAIL.EXT_OLIST_GEO;