CREATE TABLE CE_SUPPLIERS (
    SUPPLIER_ID NUMBER,
    SUPPLIER_SRCID VARCHAR2(250) NOT NULL,
    SOURCE_SYSTEM VARCHAR2(50) NOT NULL,
    SOURCE_TABLE VARCHAR2(50) NOT NULL,
    SUPPLIER_NAME VARCHAR2(100) NOT NULL,
    SUPPLIER_SECTOR VARCHAR2(100) NOT NULL,
    SUPPLIER_CITY_ID NUMBER,
    INSERT_DT DATE NOT NULL,
    UPDATE_DT DATE NOT NULL,
    CONSTRAINT PK_SUPPLIERS PRIMARY KEY(SUPPLIER_ID),
    CONSTRAINT FK_SUPPLIERS FOREIGN KEY (SUPPLIER_CITY_ID)
    REFERENCES CE_CITIES(CITY_ID)
);

CREATE OR REPLACE PUBLIC SYNONYM CE_SUPPLIERS FOR BL_3NF.CE_SUPPLIERS;
GRANT SELECT, INSERT, UPDATE, DELETE ON BL_3NF.CE_SUPPLIERS TO BL_CL;