INSERT INTO SA_SOURCE_SYSTEM_RETAIL.SA_LOGISTIC_PARTNERS
(
    LOGISTIC_PARTNER_ID, 
	LOGISTIC_PARTNER_NAME, 
	CITY_ID
)
SELECT 
    TO_NUMBER(LOGISTIC_PARTNER_ID),
	LOGISTIC_PARTNER_NAME,
    TO_NUMBER(REGEXP_REPLACE(CITY_ID, '[^[:digit:]]', '')) AS CITY_ID
FROM SA_SOURCE_SYSTEM_RETAIL.EXT_LOGISTIC_PARTNERS;

COMMIT;