CREATE OR REPLACE PACKAGE PKG_ETL_CE AS 
    PROCEDURE LD_CE_LOGISTIC_PARTNERS;
    PROCEDURE LD_CE_SUPPLIERS;
    PROCEDURE LD_CE_PAYMENT_TYPES;
    PROCEDURE LD_CE_CITIES;
    PROCEDURE LD_CE_STATES;
    PROCEDURE LD_CE_COUNTRIES;
    PROCEDURE LD_CE_CUSTOMERS;
    PROCEDURE LD_CE_PRODUCTS_CATEGORIES_SCD;
    PROCEDURE LD_CE_PRODUCTS_SCD;
    PROCEDURE LD_CE_SALES_RETAIL;
    PROCEDURE LD_CE_SALES_BUSINESS;
    PROCEDURE LD_CE_SALES_MAIN;
END PKG_ETL_CE;