INSERT INTO SA_SOURCE_SYSTEM_RETAIL.SA_SALES
(
    ORDER_ID, 
	PAYMENT_TYPE, 
	PRODUCT_ID, 
	CUSTOMER_ID, 
	SUPPLIER_ID, 
	LOGISTIC_PARTNER_ID, 
	PAYMENT_VALUE, 
	COST_VALUE, 
	PURCHASE_DATE 
)
SELECT
    ORDER_ID, 
	PAYMENT_TYPE, 
	PRODUCT_ID, 
	CUSTOMER_ID, 
	SUPPLIER_ID, 
	TO_NUMBER(LOGISTIC_PARTNER_ID), 
	TO_NUMBER(PAYMENT_VALUE, '99999.99'), 
	TO_NUMBER(COST_VALUE, '99999.99'), 
	TO_DATE(PURCHASE_DATE, 'YYYY-MM-DD')
FROM SA_SOURCE_SYSTEM_RETAIL.EXT_SALES;

COMMIT;