CREATE TABLE FCT_SALES_DD (
    ORDER_ID                    NUMBER NOT NULL,
    SOURCE_SYSTEM               VARCHAR2(100) NOT NULL,
    SOURCE_TABLE                VARCHAR2(100) NOT NULL,
    EVENT_DT                    DATE NOT NULL,
    PRODUCT_SURR_ID             NUMBER NOT NULL,
    CUSTOMER_SURR_ID            NUMBER NOT NULL,
    SUPPLIER_SURR_ID            NUMBER NOT NULL,
    PAYMENT_TYPE_SURR_ID        NUMBER NOT NULL,
    LOGISTIC_PARTNERS_SURR_ID   NUMBER NOT NULL,
    GEOLOCATION_SURR_ID         NUMBER NOT NULL,
    FCT_PRODUCT_AMOUNT_SOLD     NUMBER,
    FCT_PRODUCT_COST            NUMBER,
    INSERT_DT                   DATE NOT NULL,
    UPDATE_DT                   DATE NOT NULL
)
PARTITION BY RANGE(INSERT_DT)
(
  PARTITION SALES_07_19 VALUES LESS THAN (TO_DATE('2019-08-01', 'YYYY-MM-DD')),
  PARTITION SALES_08_19 VALUES LESS THAN (TO_DATE('2019-09-01', 'YYYY-MM-DD')),
  PARTITION SALES_09_19 VALUES LESS THAN (TO_DATE('2019-10-01', 'YYYY-MM-DD')),
  PARTITION SALES_10_19 VALUES LESS THAN (TO_DATE('2019-11-01', 'YYYY-MM-DD')),
  PARTITION SALES_11_19 VALUES LESS THAN (TO_DATE('2019-12-01', 'YYYY-MM-DD')),
  PARTITION SALES_12_19 VALUES LESS THAN (TO_DATE('2020-01-01', 'YYYY-MM-DD')),
  PARTITION SALES_01_20 VALUES LESS THAN (TO_DATE('2020-02-01', 'YYYY-MM-DD')),
  PARTITION SALES_02_20 VALUES LESS THAN (TO_DATE('2020-03-01', 'YYYY-MM-DD')),
  PARTITION SALES_03_20 VALUES LESS THAN (TO_DATE('2020-04-01', 'YYYY-MM-DD')),
  PARTITION SALES_04_20 VALUES LESS THAN (TO_DATE('2020-05-01', 'YYYY-MM-DD')),
  PARTITION SALES_05_20 VALUES LESS THAN (TO_DATE('2020-06-01', 'YYYY-MM-DD')),
  PARTITION SALES_06_20 VALUES LESS THAN (TO_DATE('2020-07-01', 'YYYY-MM-DD')),
  PARTITION SALES_07_20 VALUES LESS THAN (TO_DATE('2020-08-01', 'YYYY-MM-DD')),
  PARTITION SALES_08_20 VALUES LESS THAN (TO_DATE('2020-09-01', 'YYYY-MM-DD')),
  PARTITION SALES_09_20 VALUES LESS THAN (TO_DATE('2020-10-01', 'YYYY-MM-DD')),
  PARTITION SALES_10_20 VALUES LESS THAN (TO_DATE('2020-11-01', 'YYYY-MM-DD')),
  PARTITION SALES_11_20 VALUES LESS THAN (TO_DATE('2020-12-01', 'YYYY-MM-DD')),
  PARTITION SALES_12_20 VALUES LESS THAN (TO_DATE('2021-01-01', 'YYYY-MM-DD')),
  PARTITION SALES_01_21 VALUES LESS THAN (TO_DATE('2021-02-01', 'YYYY-MM-DD')),
  PARTITION max_val VALUES LESS THAN (maxvalue)
);


GRANT SELECT, INSERT, UPDATE, DELETE ON FCT_SALES_DD TO BL_CL;
CREATE PUBLIC SYNONYM FCT_SALES_DD FOR BL_DM.FCT_SALES_DD;