INSERT INTO  SA_SOURCE_SYSTEM_RETAIL.SA_CUSTOMERS_RETAIL
(
    CUSTOMER_ID, 
	CUSTOMER_ID_NUM, 
	CUSTOMER_UNIQUE_ID, 
	CUSTOMER_UNIQUE_ID_NUM, 
	CUSTOMER_CITY, 
	CUSTOMER_STATE, 
	FIRST_NAME, 
	LAST_NAME 
)
SELECT
    CUSTOMER_ID,
    TO_NUMBER(CUSTOMER_ID_NUM),
    CUSTOMER_UNIQUE_ID,
    TO_NUMBER(CUSTOMER_UNIQUE_ID_NUM),
    CUSTOMER_CITY,
    CUSTOMER_STATE,
    FIRST_NAME,
    LAST_NAME
FROM SA_SOURCE_SYSTEM_RETAIL.EXT_CUSTOMERS_RETAIL;

COMMIT;