CREATE TABLE PRM_MTA_INCREMENTAL_LOAD (
    SA_TABLE_NAME VARCHAR2(100) NOT NULL,
    TARGET_TABLE_NAME VARCHAR2(100) NOT NULL,
    PACKAGE_NAME VARCHAR2(100) NOT NULL,
    PROCEDURE_NAME VARCHAR2(100) NOT NULL,
    PREVIOUS_LOADED_DATE DATE NOT NULL
);