CREATE TABLE DIM_GEOLOCATIONS (
    GEOLOCATION_SURR_ID     NUMBER,
    SOURCE_SYSTEM           VARCHAR2(100) NOT NULL, 
    SOURCE_TABLE            VARCHAR2(100) NOT NULL,
    GEOLOCATION_CITY_ID     NUMBER NOT NULL,
    GEOLOCATION_CITY_NAME   VARCHAR2(50) NOT NULL,
    GEOLOCATION_STATE_ID    NUMBER NOT NULL,
    GEOLOCATION_STATE_NAME  VARCHAR2(50) NOT NULL,
    GEOLOCATION_COUNTRY_ID    NUMBER NOT NULL,
    GEOLOCATION_COUNTRY_NAME  VARCHAR2(50) NOT NULL,
    INSERT_DT               DATE NOT NULL,
    UPDATE_DT               DATE NOT NULL,
    CONSTRAINT PK_DIM_GEOLOCATIONS PRIMARY KEY (GEOLOCATION_SURR_ID)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON DIM_GEOLOCATIONS TO BL_CL;
CREATE PUBLIC SYNONYM DIM_GEOLOCATIONS FOR BL_DM.DIM_GEOLOCATIONS;