CREATE TABLE DIM_PAYMENT_TYPES (
    PAYMENT_TYPE_SURR_ID NUMBER,
    PAYMENT_TYPE_ID      NUMBER NOT NULL,
    SOURCE_SYSTEM        VARCHAR2(100) NOT NULL,
    SOURCE_TABLE         VARCHAR2(100) NOT NULL,
    PAYMENT_TYPE_NAME    VARCHAR2(30) NOT NULL,
    INSERT_DT            DATE NOT NULL,
    UPDATE_DT            DATE NOT NULL,
    CONSTRAINT PK_DIM_PAYMENT_TYPES PRIMARY KEY (PAYMENT_TYPE_SURR_ID) 
);

GRANT SELECT, INSERT, UPDATE, DELETE ON DIM_PAYMENT_TYPES TO BL_CL;
CREATE PUBLIC SYNONYM DIM_PAYMENT_TYPES FOR BL_DM.DIM_PAYMENT_TYPES;