CREATE SEQUENCE SEQ_DIM_GEOLOCATIONS_SURR
    START WITH 1;
    

GRANT SELECT ON SEQ_DIM_GEOLOCATIONS_SURR TO BL_CL;
CREATE PUBLIC SYNONYM SEQ_DIM_GEOLOCATIONS_SURR FOR BL_DM.SEQ_DIM_GEOLOCATIONS_SURR;