CREATE TABLE CE_COUNTRIES (
    COUNTRY_ID NUMBER,
    COUNTRY_SRCID NUMBER,
    SOURCE_SYSTEM VARCHAR2(50) NOT NULL,
    SOURCE_TABLE VARCHAR2(50) NOT NULL,
    COUNTRY_NAME VARCHAR2(50) NOT NULL,
    INSERT_DT DATE,
    UPDATE_DT DATE,
    CONSTRAINT PK_COUNTRIES PRIMARY KEY(COUNTRY_ID)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON BL_3NF.CE_COUNTRIES TO BL_CL;
CREATE OR REPLACE PUBLIC SYNONYM CE_COUNTRIES FOR BL_3NF.CE_COUNTRIES;