CREATE TABLE SA_PAYMENTS_TYPES (
  PAYMENT_TYPE_ID       NUMBER,
  PAYMENT_TYPE_NAME     VARCHAR2(250),
  INSERT_DATE   DATE DEFAULT CURRENT_DATE
);

GRANT SELECT, INSERT ON SA_PAYMENTS_TYPES TO BL_CL;
CREATE OR REPLACE PUBLIC SYNONYM SA_PAYMENTS_TYPES FOR SA_SOURCE_SYSTEM_RETAIL.SA_PAYMENTS_TYPES;