CREATE OR REPLACE PACKAGE PKG_ETL_DIM AS 
    PROCEDURE LD_DIM_DATES;
    PROCEDURE LD_DIM_GEOLOCATIONS;
    PROCEDURE LD_DIM_PAYMENT_TYPES;
    PROCEDURE LD_DIM_SUPPLIERS;
    PROCEDURE LD_DIM_CUSTOMERS;
    PROCEDURE LD_DIM_LOGISTIC_PARTNERS;
    PROCEDURE LD_DIM_PRODUCTS_SCD;
    PROCEDURE LD_FCT_SALES_DD_INIT;
    PROCEDURE LD_FCT_SALES_DD_REG (CURR_DATE DATE);
END PKG_ETL_DIM;