INSERT INTO BL_3NF.CE_SUPPLIERS 
(
    SUPPLIER_SRCID,
    SOURCE_SYSTEM,
    SOURCE_TABLE,
    SUPPLIER_NAME,
    SUPPLIER_SECTOR,
    SUPPLIER_CITY_ID
)

WITH TEMP_Q AS 
(
    SELECT 
        MAX(INSERT_DT) AS MAX_DATE
    FROM BL_3NF.CE_SUPPLIERS
)
SELECT 
    SUPPLIER_ID,
    'SA_SOURCE_SYSTEM_RETAIL',
    'SA_OLIST_GEO',
    NVL(SUPPLIER_NAME, 'N/A'),
    SECTOR,
    NVL((SELECT CITY_ID FROM BL_3NF.CE_CITIES NF WHERE LOWER(NF.CITY_NAME) = 
         LOWER(SA.SUPPLIER_CITY) and ROWNUM <= 1), -1) SUPPLIER_CITY
FROM SA_SOURCE_SYSTEM_RETAIL.SA_OLIST_SUPPLIERS_DATASET SA
WHERE INSERT_DATE > (SELECT MAX_DATE FROM TEMP_Q)
    AND SUPPLIER_ID NOT IN (
                                SELECT
                                    SUPPLIER_SRCID
                                FROM BL_3NF.CE_SUPPLIERS
                            )
;

COMMIT;