CREATE TABLE EXT_PRODUCTS (
  PRODUCT_ID		             VARCHAR2(250),
  PRODUCT_ID_NUM                 VARCHAR2(250),
  PRODUCT_NAME	                 VARCHAR2(250),
  PRODUCT_CATEGORY_ID            VARCHAR2(250),
  PRODUCT_CATEGORY_NAME_ENGLISH  VARCHAR2(250),
  PRODUCT_CATEGORY_MARGIN_RATE   VARCHAR2(250),
  PRODUCT_WEIGHT_G	             VARCHAR2(250),
  PRODUCT_LENGTH_CM              VARCHAR2(250),
  PRODUCT_HEIGHT_CM              VARCHAR2(250),
  PRODUCT_WIDTH_CM               VARCHAR2(250)
)
ORGANIZATION EXTERNAL (
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY EXT_DIR_RETAIL_DATA
  ACCESS PARAMETERS (
    RECORDS DELIMITED BY NEWLINE 
    SKIP 1
    FIELDS TERMINATED BY ','
    OPTIONALLY ENCLOSED BY '"'
    MISSING FIELD VALUES ARE NULL
  )
  LOCATION ('products.csv')
)
REJECT LIMIT UNLIMITED;

CREATE OR REPLACE PUBLIC SYNONYM EXT_PRODUCTS FOR SA_SOURCE_SYSTEM_RETAIL.EXT_PRODUCTS;
GRANT SELECT ON EXT_PRODUCTS TO BL_CL;