INSERT INTO BL_3NF.CE_CUSTOMERS 
(
	CUSTOMER_SRCID, 
	SOURCE_SYSTEM, 
	SOURCE_TABLE, 
	CUSTOMER_FIRST_NAME, 
	CUSTOMER_LAST_NAME, 
	CUSTOMER_COMPANY_NAME, 
	CUSTOMER_CITY_ID, 
	IS_COMPANY
)

-- identifying of last insert date to BL_3NF.CE_CUSTOMERS 
WITH TEMP_Q AS 
(
    SELECT 
        MAX(INSERT_DT) AS MAX_DATE
    FROM BL_3NF.CE_CUSTOMERS
)

-- inserting rows from two source systems to BL_3NF.CE_CUSTOMERS 
-- which have got insert date greater then  MAX_DATE from CTE TEMP_Q
SELECT 
    CUSTOMER_ID,
    'SA_SOURCE_SYSTEM_RETAIL' AS SOURCE_SYSTEM,
    'SA_CUSTOMERS_RETAIL' AS SOURCE_TABLE,
    FIRST_NAME,
    LAST_NAME,
    'N/A' AS COMPANY_NAME,
    NVL((SELECT CITY_ID FROM BL_3NF.CE_CITIES NF WHERE LOWER(NF.CITY_NAME) = 
         LOWER(SA.CUSTOMER_CITY) and ROWNUM <= 1), -1) AS CUSTOMER_CITY_ID,
    'N' AS IS_COMPANY
FROM SA_SOURCE_SYSTEM_RETAIL.SA_CUSTOMERS_RETAIL SA
WHERE INSERT_DATE > (SELECT MAX_DATE FROM TEMP_Q)

UNION ALL

SELECT 
    TO_CHAR(CUSTOMER_ID),
    'SA_SOURCE_SYSTEM_BUSINESS' AS SOURCE_SYSTEM,
    'SA_CUSTOMERS_BUSINESS' AS SOURCE_TABLE,
    'N/A' AS FIRST_NAME,
    'N/A' AS LAST_NAME,
    COMPANY_NAME,
    NVL((SELECT CITY_ID FROM BL_3NF.CE_CITIES NF WHERE LOWER(NF.CITY_NAME) = 
         LOWER(SA.COMPANY_CITY) and ROWNUM <= 1), -1) AS CUSTOMER_CITY_ID,
    'Y' AS IS_COMPANY     
FROM SA_SOURCE_SYSTEM_BUSINESS.SA_CUSTOMERS_BUSINESS SA
WHERE INSERT_DATE > (SELECT MAX_DATE FROM TEMP_Q);


COMMIT;



