CREATE TABLE CE_CITIES (
    CITY_ID NUMBER,
    CITY_SRCID NUMBER,
    SOURCE_SYSTEM VARCHAR2(50) NOT NULL,
    SOURCE_TABLE VARCHAR2(50) NOT NULL,
    CITY_NAME VARCHAR2(50) NOT NULL,
    CITY_STATE_ID NUMBER,
    INSERT_DT DATE,
    UPDATE_DT DATE,
    CONSTRAINT PK_CITIES PRIMARY KEY(CITY_ID),
    CONSTRAINT FK_CITIES FOREIGN KEY (CITY_STATE_ID)
    REFERENCES CE_STATES(STATE_ID)
);

CREATE OR REPLACE PUBLIC SYNONYM CE_CITIES FOR BL_3NF.CE_CITIES;
GRANT SELECT, INSERT, UPDATE, DELETE  ON BL_3NF.CE_CITIES TO BL_CL;