CREATE TABLE DIM_CUSTOMERS (
    CUSTOMER_SURR_ID     NUMBER,
    CUSTOMER_ID          NUMBER NOT NULL,
    SOURCE_SYSTEM        VARCHAR2(50) NOT NULL,
    SOURCE_TABLE         VARCHAR2(50) NOT NULL,
    CUSTOMER_FIRST_NAME  VARCHAR2(50) NOT NULL,
    CUSTOMER_LAST_NAME   VARCHAR2(50) NOT NULL,
    CUSTOMER_COMPANY_NAME VARCHAR2(100) NOT NULL,
    CUSTOMER_CITY_ID     NUMBER NOT NULL,
    CUSTOMER_CITY_NAME   VARCHAR2(50) NOT NULL,
    CUSTOMER_STATE_ID    NUMBER NOT NULL,
    CUSTOMER_STATE_NAME  VARCHAR2(50) NOT NULL,
    IS_COMPANY           VARCHAR2(4) NOT NULL,
    INSERT_DT            DATE NOT NULL,
    UPDATE_DT            DATE NOT NULL,
    CONSTRAINT PK_DIM_CUSTOMERS PRIMARY KEY (CUSTOMER_SURR_ID)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON DIM_CUSTOMERS TO BL_CL;
CREATE PUBLIC SYNONYM DIM_CUSTOMERS FOR BL_DM.DIM_CUSTOMERS;