ALTER SESSION SET "_ORACLE_SCRIPT" = true;

CREATE USER SA_SOURCE_SYSTEM_RETAIL IDENTIFIED BY SA_SOURCE_SYSTEM_RETAIL
 DEFAULT TABLESPACE users
 TEMPORARY TABLESPACE temp
 PROFILE default;
GRANT connect, resource TO SA_SOURCE_SYSTEM_RETAIL;
GRANT UNLIMITED TABLESPACE TO SA_SOURCE_SYSTEM_RETAIL;

CREATE OR REPLACE DIRECTORY EXT_DIR_RETAIL_DATA as 
'/opt/oracle/oradata/retail_data_set';

GRANT READ, WRITE ON DIRECTORY EXT_DIR_RETAIL_DATA TO SA_SOURCE_SYSTEM_RETAIL;
GRANT READ, WRITE ON DIRECTORY EXT_DIR_RETAIL_DATA TO BL_CL;
GRANT CREATE PUBLIC SYNONYM TO SA_SOURCE_SYSTEM_RETAIL;