CREATE TABLE DIM_LOGISTIC_PARTNERS (
    LOGISTIC_PARTNERS_SURR_ID     NUMBER,
    LOGISTIC_PARTNERS_ID          NUMBER NOT NULL,
    SOURCE_SYSTEM                 VARCHAR2(100) NOT NULL,
    SOURCE_TABLE                  VARCHAR2(100) NOT NULL,
    LOGISTIC_PARTNERS_NAME        VARCHAR2(50) NOT NULL,
    LOGISTIC_PARTNERS_CITY_ID     NUMBER NOT NULL,
    LOGISTIC_PARTNERS_CITY_NAME   VARCHAR2(50) NOT NULL,
    LOGISTIC_PARTNERS_STATE_ID    NUMBER NOT NULL,
    LOGISTIC_PARTNERS_STATE_NAME  VARCHAR2(50) NOT NULL,
    INSERT_DT                     DATE NOT NULL,
    UPDATE_DT                     DATE NOT NULL,
    CONSTRAINT PK_DIM_LOGISTIC_PARTNERS PRIMARY KEY (LOGISTIC_PARTNERS_SURR_ID)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON DIM_LOGISTIC_PARTNERS TO BL_CL;
CREATE PUBLIC SYNONYM DIM_LOGISTIC_PARTNERS FOR BL_DM.DIM_LOGISTIC_PARTNERS;