INSERT INTO SA_SOURCE_SYSTEM_BUSINESS.SA_SALES_BUSINESS 
(
    ORDER_ID, 
	PAYMENT_TYPE, 
	PRODUCT_ID, 
	CUSTOMER_ID, 
	SUPPLIER_ID, 
	LOGISTIC_PARTNER_ID, 
	PAYMENT_VALUE, 
	COST_VALUE, 
	PURCHASE_DATE 
)
SELECT
    ORDER_ID, 
	PAYMENT_TYPE, 
	PRODUCT_ID, 
	CUSTOMER_ID, 
	SUPPLIER_ID, 
	TO_NUMBER(LOGISTIC_PARTNER_ID), 
	TO_NUMBER(PAYMENT_VALUE, '9999999.99'), 
	TO_NUMBER(COST_VALUE, '9999999.99'), 
	TO_DATE(PURCHASE_DATE, 'YYYY-MM-DD') 
FROM SA_SOURCE_SYSTEM_BUSINESS.EXT_SALES_BUSINESS;

COMMIT;