INSERT INTO BL_3NF.CE_LOGISTIC_PARTNERS 
( 
	LOGISTIC_PARTNER_SRCID, 
	SOURCE_SYSTEM, 
	SOURCE_TABLE, 
	LOGISTIC_PARTNER_NAME, 
	LOGISTIC_PARTNER_CITY_ID
)
WITH TEMP_Q AS 
(
    SELECT 
        MAX(INSERT_DT) AS MAX_DATE
    FROM BL_3NF.CE_LOGISTIC_PARTNERS
)
SELECT
    LOGISTIC_PARTNER_ID,
    'SA_SOURCE_SYSTEM_RETAIL' AS SOURCE_SYSTEM,
    'SA_LOGISTIC_PARTNERS' AS SOURCE_TABLE,
    LOGISTIC_PARTNER_NAME,
    CITY_ID
FROM SA_SOURCE_SYSTEM_RETAIL.SA_LOGISTIC_PARTNERS
WHERE INSERT_DATE > (SELECT MAX_DATE FROM TEMP_Q) AND 
LOGISTIC_PARTNER_ID NOT IN (
                                SELECT
                                    LOGISTIC_PARTNER_SRCID
                                FROM BL_3NF.CE_LOGISTIC_PARTNERS
                            );

COMMIT;