INSERT INTO BL_3NF.CE_LOGISTIC_PARTNERS 
(
    LOGISTIC_PARTNER_ID, 
	LOGISTIC_PARTNER_SRCID, 
	SOURCE_SYSTEM, 
	SOURCE_TABLE, 
	LOGISTIC_PARTNER_NAME, 
	LOGISTIC_PARTNER_CITY_ID, 
	INSERT_DT, 
	UPDATE_DT
)
VALUES (-1, -99, 'N/A', 'N/A', 'N/A', -1, TO_DATE('1990-01-01', 'YYYY-MM-DD'),
TO_DATE('1990-01-01', 'YYYY-MM-DD'));

COMMIT;