INSERT INTO SA_SOURCE_SYSTEM_RETAIL.SA_PAYMENTS_TYPES 
(
    PAYMENT_TYPE_ID,
    PAYMENT_TYPE_NAME
)
SELECT
    TO_NUMBER(PAYMENT_TYPE_ID),
    PAYMENT_TYPE_NAME
FROM SA_SOURCE_SYSTEM_RETAIL.EXT_PAYMENTS_TYPES;

COMMIT;
