INSERT INTO BL_3NF.CE_SALES
(
    SALE_ID, 
	SALE_SRCID, 
	SOURCE_SYSTEM, 
	SOURCE_TABLE, 
	PRODUCT_ID, 
	CUSTOMER_ID, 
	SUPPLIER_ID, 
	LOGISTIC_PARTNER_ID, 
	PAYMENT_TYPE_ID, 
	AMOUNT_VALUE, 
	COST_VALUE, 
	PURCHASE_DATE, 
	INSERT_DT, 
	UPDATE_DT
)
VALUES(-1, '-99', 'N/A', 'N/A', -1, -1, -1, -1, -1, 0, 0, 
TO_DATE('1900-01-01', 'YYYY-MM-DD'), TO_DATE('1900-01-01', 'YYYY-MM-DD'),
TO_DATE('1900-01-01', 'YYYY-MM-DD'))
;

COMMIT;