CREATE TABLE EXT_PAYMENTS_TYPES (
  PAYMENT_TYPE_ID       VARCHAR2(250),
  PAYMENT_TYPE_NAME     VARCHAR2(250)   
)
ORGANIZATION EXTERNAL (
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY EXT_DIR_RETAIL_DATA
  ACCESS PARAMETERS (
    RECORDS DELIMITED BY NEWLINE 
    SKIP 1
    FIELDS TERMINATED BY ','
    OPTIONALLY ENCLOSED BY '"'
    MISSING FIELD VALUES ARE NULL
  )
  LOCATION ('payments_types.csv')
)
REJECT LIMIT UNLIMITED;


GRANT SELECT ON EXT_PAYMENTS_TYPES TO BL_CL;
CREATE OR REPLACE PUBLIC SYNONYM EXT_PAYMENTS_TYPES FOR SA_SOURCE_SYSTEM_RETAIL.EXT_PAYMENTS_TYPES;