CREATE TABLE SA_LOGISTIC_PARTNERS (
  LOGISTIC_PARTNER_ID    NUMBER,
  LOGISTIC_PARTNER_NAME  VARCHAR2(250),
  CITY_ID	             NUMBER,
  INSERT_DATE   DATE DEFAULT CURRENT_DATE
);

GRANT SELECT, INSERT ON SA_LOGISTIC_PARTNERS TO BL_CL;

CREATE OR REPLACE PUBLIC SYNONYM SA_LOGISTIC_PARTNERS FOR SA_SOURCE_SYSTEM_RETAIL.SA_LOGISTIC_PARTNERS;