CREATE TABLE EXT_SALES (
  ORDER_ID		       VARCHAR2(250),
  PAYMENT_TYPE         VARCHAR2(250),
  PRODUCT_ID	       VARCHAR2(250),
  CUSTOMER_ID	       VARCHAR2(250),
  SUPPLIER_ID          VARCHAR2(250),
  LOGISTIC_PARTNER_ID  VARCHAR2(250),
  PAYMENT_VALUE	       VARCHAR2(250),
  COST_VALUE           VARCHAR2(250),
  PURCHASE_DATE        VARCHAR2(250)
)
ORGANIZATION EXTERNAL (
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY EXT_DIR_RETAIL_DATA
  ACCESS PARAMETERS (
    RECORDS DELIMITED BY NEWLINE 
    SKIP 1
    FIELDS TERMINATED BY ','
    OPTIONALLY ENCLOSED BY '"'
    MISSING FIELD VALUES ARE NULL
  )
  LOCATION ('payments_retail.csv')
)
REJECT LIMIT UNLIMITED;

CREATE OR REPLACE PUBLIC SYNONYM EXT_SALES FOR SA_SOURCE_SYSTEM_RETAIL.EXT_SALES;
GRANT SELECT ON EXT_SALES TO BL_CL;