CREATE TABLE EXT_LOGISTIC_PARTNERS (
  LOGISTIC_PARTNER_ID    VARCHAR2(250),
  LOGISTIC_PARTNER_NAME  VARCHAR2(250),
  CITY_ID	             VARCHAR2(250)
)
ORGANIZATION EXTERNAL (
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY EXT_DIR_RETAIL_DATA
  ACCESS PARAMETERS (
    RECORDS DELIMITED BY NEWLINE 
    SKIP 1
    FIELDS TERMINATED BY ','
    OPTIONALLY ENCLOSED BY '"'
    MISSING FIELD VALUES ARE NULL
  )
  LOCATION ('logistic partners.csv')
)
REJECT LIMIT UNLIMITED;

CREATE OR REPLACE PUBLIC SYNONYM EXT_LOGISTIC_PARTNERS FOR SA_SOURCE_SYSTEM_RETAIL.EXT_LOGISTIC_PARTNERS;

GRANT SELECT ON EXT_LOGISTIC_PARTNERS TO BL_CL;