CREATE SEQUENCE SEQ_DIM_PAYMENT_TYPES_SURR
    START WITH 1;
    
GRANT SELECT ON SEQ_DIM_PAYMENT_TYPES_SURR TO BL_CL;
CREATE PUBLIC SYNONYM SEQ_DIM_PAYMENT_TYPES_SURR FOR BL_DM.SEQ_DIM_PAYMENT_TYPES_SURR;