CREATE TABLE EXT_CUSTOMERS_RETAIL (
  CUSTOMER_ID	          VARCHAR2(250),
  CUSTOMER_ID_NUM         VARCHAR2(250),
  CUSTOMER_UNIQUE_ID	  VARCHAR2(250),
  CUSTOMER_UNIQUE_ID_NUM  VARCHAR2(250),
  CUSTOMER_CITY	          VARCHAR2(250),
  CUSTOMER_STATE          VARCHAR2(250),
  FIRST_NAME              VARCHAR2(250),
  LAST_NAME               VARCHAR2(250)
)
ORGANIZATION EXTERNAL (
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY EXT_DIR_RETAIL_DATA
  ACCESS PARAMETERS (
    RECORDS DELIMITED BY NEWLINE 
    SKIP 1
    FIELDS TERMINATED BY ','
    OPTIONALLY ENCLOSED BY '"'
    MISSING FIELD VALUES ARE NULL
  )
  LOCATION ('customers_retail.csv')
)
REJECT LIMIT UNLIMITED;

GRANT SELECT ON EXT_CUSTOMERS_RETAIL TO BL_CL;
CREATE OR REPLACE PUBLIC SYNONYM EXT_CUSTOMERS_RETAIL FOR SA_SOURCE_SYSTEM_RETAIL.EXT_CUSTOMERS_RETAIL;